# Automated Exam Evaluation System (NLP-based descriptive answer grading)
### This project aims to automate the grading process for student essays using Natural Language Processing (NLP) and Machine Learning. It utilises the ASAP-AES dataset to build a regressor that can predict essay scores based on the semantic content of the text.

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving asap-aes.zip to asap-aes.zip

In [ ]:
!unzip asap-aes.zip

Archive:  asap-aes.zip
  inflating: Essay_Set_Descriptions.zip
  inflating: Training_Materials.zip
  inflating: test_set.tsv
  inflating: training_set_rel3.tsv
  inflating: training_set_rel3.xls
  inflating: training_set_rel3.xlsx
  inflating: valid_sample_submission_1_column.csv
  inflating: valid_sample_submission_1_column_no_header.csv
  inflating: valid_sample_submission_2_column.csv
  inflating: valid_sample_submission_5_column.csv
  inflating: valid_set.tsv
  inflating: valid_set.xls
  inflating: valid_set.xlsx

In [ ]:
!pip install sentence-transformers scikit-learn pandas

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.2.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.5.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cu128)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.25.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.3.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.24.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.11.0->sentence-transformers) (1.4.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (0.1.2)

# Importing lib and model

In [ ]:
import pandas as pd
import numpy as np

from sentence_transformers import SentenceTransformer

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
!pip install sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.2.3)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.5.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cu128)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.25.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.3.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.24.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.11.0->sentence-transformers) (1.4.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (0.1.2)

###In order to process and understand the textual content of student essays, I use a pre-trained Sentence-BERT model. Sentence-BERT is a modification of the BERT transformer model that is specifically designed to generate semantic embeddings for sentences and paragraphs. These embeddings convert text into numerical vectors that capture the meaning and context of the essay.

### In this project, I used the model (all-MiniLM-L6-v2), which is a lightweight and efficient Sentence-BERT model that produces 384-dimensional vector representations of text.

In [ ]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

#Essay Set	Score Range
###Set 1	2 – 12
###Set 2	1 – 6
###Set 3	0 – 3
###Set 4	0 – 3
###Set 5	0 – 4
###Set 6	0 – 4
###Set 7	0 – 30
###Set 8	0 – 60

# For Set 1

In [ ]:
import pandas as pd

data = pd.read_csv(
    "training_set_rel3.tsv",
    sep="\t",
    encoding="latin-1"
)

data.head()

,essay_id,essay_set,essay,rater1_domain1,rater2_domain1,rater3_domain1,domain1_score,rater1_domain2,rater2_domain2,domain2_score,...,rater2_trait3,rater2_trait4,rater2_trait5,rater2_trait6,rater3_trait1,rater3_trait2,rater3_trait3,rater3_trait4,rater3_trait5,rater3_trait6
0,1,1,"Dear local newspaper, I think effects computer...",4,4,NaN,8,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,1,"Dear @CAPS1 @CAPS2, I believe that using compu...",5,4,NaN,9,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,1,"Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...",4,3,NaN,7,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,1,"Dear Local Newspaper, @CAPS1 I have found that...",5,5,NaN,10,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,1,"Dear @LOCATION1, I know having computers has a...",4,4,NaN,8,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
print(df.columns)

Index(['text', 'score'], dtype='object')

In [ ]:
df = data[data['essay_set'] == 1]
df = df[['essay', 'domain1_score']]

df = df.dropna()

df.head()

                                               essay  domain1_score
0  Dear local newspaper, I think effects computer...              8
1  Dear @CAPS1 @CAPS2, I believe that using compu...              9
2  Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...              7
3  Dear Local Newspaper, @CAPS1 I have found that...             10
4  Dear @LOCATION1, I know having computers has a...              8

In [ ]:
df.rename(columns={
    'essay': 'text',
    'domain1_score': 'score'
}, inplace=True)

In [ ]:
texts = df['text']
scores = df['score']

In [ ]:
embeddings = model.encode(
    texts.tolist(),
    show_progress_bar=True
)

Batches:   0%|          | 0/56 [00:00<?, ?it/s]

### The dataset is divided into two parts: a training set and a testing set. In this project, I use an 80–20 split, where 80% of the data is used to train the model and 20% is used to test and evaluate the model's performance.

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    embeddings,
    scores,
    test_size=0.2,
    random_state=42
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 1426
Testing samples: 357

###In this project, I used a Random Forest Regressor to predict the essay score based on the embeddings generated from the Sentence-BERT model. Random Forest is an ensemble machine learning algorithm that combines multiple decision trees to make more accurate predictions. Instead of relying on a single decision tree, Random Forest builds many trees during training and then averages their predictions to produce the final output.

In [ ]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=200, n_jobs=-1, random_state=42)

###Mean Squared Error (MSE) is a common evaluation metric used for regression models. MSE measures the average of the squared differences between the actual scores given by human graders and the scores predicted by the model. A smaller MSE value indicates that the predicted scores are closer to the true scores, meaning the model performs better.

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score

pred = regressor.predict(X_test)
mean_error_for_set1 = mean_squared_error(y_test, pred)

print("Mean Squared Error:", mean_squared_error(y_test, pred))
print("R2 Score:", r2_score(y_test, pred))

Mean Squared Error: 1.5694617647058822
R2 Score: 0.3105393201089205

# For set 2

In [ ]:
df = data[data['essay_set'] == 2]
df = df[['essay', 'domain1_score']]

df = df.dropna()

df.head()

                                                  essay  domain1_score
1783  Certain materials being removed from libraries...              4
1784  Write a persuasive essay to a newspaper reflec...              1
1785  Do you think that libraries should remove cert...              2
1786  In @DATE1's world, there are many things found...              4
1787  In life you have the 'offensive things'. The l...              4

In [ ]:
df.rename(columns={
    'essay': 'text',
    'domain1_score': 'score'
}, inplace=True)

In [ ]:
texts = df['text']
scores = df['score']

In [ ]:
embeddings = model.encode(
    texts.tolist(),
    show_progress_bar=True
)

Batches:   0%|          | 0/57 [00:00<?, ?it/s]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    embeddings,
    scores,
    test_size=0.2,
    random_state=42
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 1440
Testing samples: 360

In [ ]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=200, n_jobs=-1, random_state=42)

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score

pred = regressor.predict(X_test)
mean_error_for_set2 = mean_squared_error(y_test, pred)

print("Mean Squared Error:", mean_squared_error(y_test, pred))
print("R2 Score:", r2_score(y_test, pred))

Mean Squared Error: 0.42339541666666664
R2 Score: 0.2594465828114877

In [ ]:
data['essay_set'].unique()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
sample_index = 45
original_df_index = y_test.index[sample_index]

sample_essay = texts[original_df_index]
sample_actual_score = y_test.iloc[sample_index]
sample_predicted_score = pred[sample_index]

print(f"Original Essay:\n{sample_essay}\n")
print(f"Actual Score: {sample_actual_score}")
print(f"Predicted Score: {sample_predicted_score}")

Original Essay:
This is what's wrong with today's society. We are too soft.We're too worried about what other people might think if we say this or do that. I'm the kind of person that doesn't care about other peoples feelings. And I say that to an extent. If we're talking about my friends, family, my girlfriend, that's totally different. I show a lot of respect to those people on a daily basis. But as far as people I don't know, I could care less what their beliefs, opinions, and outlooks on life are. Maybe we should stop worrying about other people for once and just try to grow and prosper as a race.      Anybody ever think of that? If I had it my way, the @ORGANIZATION1 would not exist. @CAPS1, radio, books, movies, magazines would all be uncensored. Is life filtered and censored? Absolutely not! So why should those things be? I'm sick and tired of people constantly sheltering their children from lifes normalcies. They've gotta learn sometime. Life isn't lollipops and rainbows. It's hard, unforgiving, and it kicks you in the teeth. You've just got to learn to adapt to it. And censorship in libraries, on @CAPS1 etc, won't and aren't helping matters in the least bit. I guess I don't understand why we have to care so much. If everybody just relaxed a little and focused on themselves, we would be fine. Everytime I hear the word 'offensive' it makes me sick to my stomach, because in my eyes, that word doesn't exist. It's a made up word that really means we care about other peoples feelings more then we do our own

Actual Score: 3
Predicted Score: 3.45

# For Set 3

In [ ]:
df = data[data['essay_set'] == 3]
df = df[['essay', 'domain1_score']]

df = df.dropna()

df.head()

                                                  essay  domain1_score
3583  The features of the setting affect the cyclist...              1
3584  The features of the setting affected the cycli...              2
3585  Everyone travels to unfamiliar places. Sometim...              1
3586  I believe the features of the cyclist affected...              1
3587  The setting effects the cyclist because of the...              2

In [ ]:
df.rename(columns={
    'essay': 'text',
    'domain1_score': 'score'
}, inplace=True)

In [ ]:
texts = df['text']
scores = df['score']

In [ ]:
embeddings = model.encode(
    texts.tolist(),
    show_progress_bar=True
)

Batches:   0%|          | 0/54 [00:00<?, ?it/s]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    embeddings,
    scores,
    test_size=0.2,
    random_state=42
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 1380
Testing samples: 346

In [ ]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=200, n_jobs=-1, random_state=42)

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score

pred = regressor.predict(X_test)
mean_error_for_set3 = mean_squared_error(y_test, pred)

print("Mean Squared Error:", mean_squared_error(y_test, pred))
print("R2 Score:", r2_score(y_test, pred))

Mean Squared Error: 0.349168780199363
R2 Score: 0.4224853250114402

In [ ]:
sample_index = 4
original_df_index = y_test.index[sample_index]

sample_essay = texts[original_df_index]
sample_actual_score = y_test.iloc[sample_index]
sample_predicted_score = pred[sample_index]

print(f"Original Essay:\n{sample_essay}\n")
print(f"Actual Score: {sample_actual_score}")
print(f"Predicted Score: {sample_predicted_score}")

Original Essay:
The features of the setting affects the cyclist in the story. In the story, it says, The water bottles contained only a few tantalizing sips. I could drop from a heatstroke. This statement clearly says that where the cyclist was riding, water was very hard to find and scare. He is talking about how he will die if he doesnt get water. Another example is that there are no buildings around and is deserted with no one around and many hills and roads. In the story it says, the terrain changing flat road was replaced by short rolling hills. This means that he was partially all by himself and he had no one to go to.

Actual Score: 2
Predicted Score: 2.12

In [ ]:
sample_index = 32
original_df_index = y_test.index[sample_index]

sample_essay = texts[original_df_index]
sample_actual_score = y_test.iloc[sample_index]
sample_predicted_score = pred[sample_index]

print(f"Original Essay:\n{sample_essay}\n")
print(f"Actual Score: {sample_actual_score}")
print(f"Predicted Score: {sample_predicted_score}")

Original Essay:
The setting clearly has a huge effect on the cyclist. The flat roads are easy and smooth to ride on, but as the road changes to short, rolling hills, the biking becomes more difficult. This is supported by the sentence that reads, "Over are long, crippling hill... This shows that the hill is a very challenging obstacle. He is also effected by the things that come with the change in terrain. For example, one sentence reads "...tumbleweeds crossed my path and a ridiculously large snake it really did look like a diamondbuck-blooked the majority of the pavement in front of me." This stresses how remote the area in which he is biking really is, and shows how it mentally and physically effects his trip.

Actual Score: 2
Predicted Score: 2.13

# For Set 4

In [ ]:
df = data[data['essay_set'] == 4]
df = df[['essay', 'domain1_score']]

df = df.dropna()

df.head()

                                                  essay  domain1_score
5309  The author concludes the story with this becau...              0
5310  The narrater has that in with Paragraph becuse...              0
5311  The author concludes the story with that passa...              3
5312  The author ended the story with this paragraph...              2
5313  The author concludes the story with this parag...              2

In [ ]:
df.rename(columns={
    'essay': 'text',
    'domain1_score': 'score'
}, inplace=True)

In [ ]:
texts = df['text']
scores = df['score']

In [ ]:
embeddings = model.encode(
    texts.tolist(),
    show_progress_bar=True
)

Batches:   0%|          | 0/56 [00:00<?, ?it/s]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    embeddings,
    scores,
    test_size=0.2,
    random_state=42
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 1416
Testing samples: 354

In [ ]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=200, n_jobs=-1, random_state=42)

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score

pred = regressor.predict(X_test)
mean_error_for_set4 = mean_squared_error(y_test, pred)

print("Mean Squared Error:", mean_squared_error(y_test, pred))
print("R2 Score:", r2_score(y_test, pred))

Mean Squared Error: 0.35490818455743883
R2 Score: 0.5912500431398138

In [ ]:
sample_index = 4
original_df_index = y_test.index[sample_index]

sample_essay = texts[original_df_index]
sample_actual_score = y_test.iloc[sample_index]
sample_predicted_score = pred[sample_index]

print(f"Original Essay:\n{sample_essay}\n")
print(f"Actual Score: {sample_actual_score}")
print(f"Predicted Score: {sample_predicted_score}")

Original Essay:
The author concludes the story with the paragraph because the geese and the hibiscus were both things that were familiar to Saeng They remind her of her homeland,When  the familiar things return ,she will have the strength to the test again and hopefully do better.The narrator says Overhead a of Canada geese flew by,their faint hunks clear and yes-fimiliar to Saeng now .This shows how the geese are a symbol of the fimilar things from her homeland that help Saeng feel more comfortable in her new home.

Actual Score: 2
Predicted Score: 1.97

In [ ]:
sample_index = 24
original_df_index = y_test.index[sample_index]

sample_essay = texts[original_df_index]
sample_actual_score = y_test.iloc[sample_index]
sample_predicted_score = pred[sample_index]

print(f"Original Essay:\n{sample_essay}\n")
print(f"Actual Score: {sample_actual_score}")
print(f"Predicted Score: {sample_predicted_score}")

Original Essay:
The authors choice of the last paragraph in the short story, Winter Hibiscus shows the hope for the future that seang feels. The winter and cold represent how she feels out of place and upset at not receiving her drivers license. In the spring she will have a piece of her homeland blooming and she will be warm again. She will feel ready to take her test again when they came back. This shows adapting to and accepting her new life away from her home and her memories. The last paragraph proves that she was strong enough to move past her hardships and move on

Actual Score: 2
Predicted Score: 2.165

# For Set 5

In [ ]:
df = data[data['essay_set'] == 5]
df = df[['essay', 'domain1_score']]

df = df.dropna()

df.head()

                                                  essay  domain1_score
7079  In this memoir of Narciso Rodriguez, @PERSON3'...              2
7080  Throughout the excerpt from Home the Blueprint...              2
7081  The mood the author created in the memoir is l...              3
7082  The mood created by the author is showing how ...              1
7083  The mood created in the memoir is happiness an...              3

In [ ]:
df.rename(columns={
    'essay': 'text',
    'domain1_score': 'score'
}, inplace=True)

In [ ]:
texts = df['text']
scores = df['score']

In [ ]:
embeddings = model.encode(
    texts.tolist(),
    show_progress_bar=True
)

Batches:   0%|          | 0/57 [00:00<?, ?it/s]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    embeddings,
    scores,
    test_size=0.2,
    random_state=42
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 1444
Testing samples: 361

In [ ]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=200, n_jobs=-1, random_state=42)

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score

pred = regressor.predict(X_test)
mean_error_for_set5 = mean_squared_error(y_test, pred)

print("Mean Squared Error:", mean_squared_error(y_test, pred))
print("R2 Score:", r2_score(y_test, pred))

Mean Squared Error: 0.3460765235457064
R2 Score: 0.6076805965118302

In [ ]:
sample_index = 16
original_df_index = y_test.index[sample_index]

sample_essay = texts[original_df_index]
sample_actual_score = y_test.iloc[sample_index]
sample_predicted_score = pred[sample_index]

print(f"Original Essay:\n{sample_essay}\n")
print(f"Actual Score: {sample_actual_score}")
print(f"Predicted Score: {sample_predicted_score}")

Original Essay:
I think the mood was happy and @CAPS1. Because They @CAPS2. The boy Loved his parents. They had to leave theirs friends. Some family there and They would miss them, but the parents wanted a better life for thier children. They were @CAPS1. to Move.

Actual Score: 1
Predicted Score: 1.095

In [ ]:
sample_index = 7
original_df_index = y_test.index[sample_index]

sample_essay = texts[original_df_index]
sample_actual_score = y_test.iloc[sample_index]
sample_predicted_score = pred[sample_index]

print(f"Original Essay:\n{sample_essay}\n")
print(f"Actual Score: {sample_actual_score}")
print(f"Predicted Score: {sample_predicted_score}")

Original Essay:
The mood in the author's story is happy and gratefull. Happy because even though it was a new country the came with a purpose and are living it with their culture which is past down family to family. "My mother and father came to this country with such couage, without any knowledge of the language or the culture. They came selflessly, as many immigrants do, to give their children a better life, even though it meant leaving behind their family, friends and careers in the country they loved." Also greatfull because he sees what his parents did and does for him so he could be happy. "I will always be gratefull to my parents for their love and sacrifice." "I was in the warmth of the kitchen in this humble house where a cuban feast always filled the air with not just scent and music but life and love!"

Actual Score: 3
Predicted Score: 2.785

# For Set 6

In [ ]:
df = data[data['essay_set'] == 6]
df = df[['essay', 'domain1_score']]

df = df.dropna()

df.head()

                                                  essay  domain1_score
8884  There were many obstacles that the builders fa...              2
8885  Him from the start, there would have been many...              3
8886  The builders of the Empire State Building face...              4
8887  In the passage The Mooring Mast by Marcia Amid...              1
8888  The builders of the Empire State Building face...              3

In [ ]:
df.rename(columns={
    'essay': 'text',
    'domain1_score': 'score'
}, inplace=True)

In [ ]:
texts = df['text']
scores = df['score']

In [ ]:
embeddings = model.encode(
    texts.tolist(),
    show_progress_bar=True
)

Batches:   0%|          | 0/57 [00:00<?, ?it/s]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    embeddings,
    scores,
    test_size=0.2,
    random_state=42
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 1440
Testing samples: 360

In [ ]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=200, n_jobs=-1, random_state=42)

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score

pred = regressor.predict(X_test)
mean_error_for_set6 = mean_squared_error(y_test, pred)

print("Mean Squared Error:", mean_squared_error(y_test, pred))
print("R2 Score:", r2_score(y_test, pred))

Mean Squared Error: 0.3721868055555556
R2 Score: 0.5815804129077029

In [ ]:
sample_index = 1
original_df_index = y_test.index[sample_index]

sample_essay = texts[original_df_index]
sample_actual_score = y_test.iloc[sample_index]
sample_predicted_score = pred[sample_index]

print(f"Original Essay:\n{sample_essay}\n")
print(f"Actual Score: {sample_actual_score}")
print(f"Predicted Score: {sample_predicted_score}")

Original Essay:
Many obstacles occured for the builers of the Empire State building and allowing dirigibles to dock there. One of these obstacles was the mooring mast itself. The winds on top of the Empire State Building were constantly shifting and if the dirigible was tied to the mooring mass it would swivel around the mooring mast. Another obstacle the builders experienced during this process was the already existing law not allowing airships to fly too low over urban areas. Due to the fact that the Empire State building was in New York, an urban area, the dirigable idea would have most likely never worked. The dirigable was unable to fulfill its destiny and the obstacles the builders faced were the main reasons.

Actual Score: 3
Predicted Score: 2.8

In [ ]:
sample_index = 25
original_df_index = y_test.index[sample_index]

sample_essay = texts[original_df_index]
sample_actual_score = y_test.iloc[sample_index]
sample_predicted_score = pred[sample_index]

print(f"Original Essay:\n{sample_essay}\n")
print(f"Actual Score: {sample_actual_score}")
print(f"Predicted Score: {sample_predicted_score}")

Original Essay:
In a desperate attempt to revolutionize the way people traveled, the idea of the mooring was not thought over as well as it should have been. The number of problems and obstacles mounted higher and higher with the idea of mooring airships to a new mast atop the Empire State Building. One of these main obstacles was, while an airship was tethered to the building it would add stress, "The stress of dirigibles load and the wind pressure would have to be transmitted all the way to the building's foundation". Another obstacle faced with the mooring mast was one of safety. Dirigibles not from the United States used hydrogen rather than helium, which is Highly flammable. Another obstacle to the construction was nature itself, with high, shifting winds due to violent air currents, a dirigible tethered to the mast would swivel around and around the Empire State Building, the only way to prevent this would be to tie the lead weights to the rear end, but massive dangling weights, hanging over one thousand feet above the public, was not the safest idea. A last obstacle that was faced with the fact that there was an existing law that prevented airships from flying too low over urban areas. These were all obstacles that should have been thought through and realized before construction for the Empire State building's mooring mast ever begin.

Actual Score: 4
Predicted Score: 3.7

# For Set 7

In [ ]:
df = data[data['essay_set'] == 7]
df = df[['essay', 'domain1_score']]

df = df.dropna()

df.head()

                                                   essay  domain1_score
10684  Patience is when your waiting .I was patience ...             15
10685  I am not a patience person, like I cant sit i...             13
10686  One day I was at basketball practice and I was...             15
10687  I going to write about a time when I went to t...             17
10688  It can be very hard for somebody to be patient...             13

In [ ]:
df.rename(columns={
    'essay': 'text',
    'domain1_score': 'score'
}, inplace=True)

In [ ]:
texts = df['text']
scores = df['score']

In [ ]:
embeddings = model.encode(
    texts.tolist(),
    show_progress_bar=True
)

Batches:   0%|          | 0/50 [00:00<?, ?it/s]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    embeddings,
    scores,
    test_size=0.2,
    random_state=42
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 1255
Testing samples: 314

In [ ]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=200, n_jobs=-1, random_state=42)

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score

pred = regressor.predict(X_test)
mean_error_for_set7 = mean_squared_error(y_test, pred)

print("Mean Squared Error:", mean_squared_error(y_test, pred))
print("R2 Score:", r2_score(y_test, pred))

Mean Squared Error: 9.590237101910828
R2 Score: 0.533118142968028

In [ ]:
sample_index = 1
original_df_index = y_test.index[sample_index]

sample_essay = texts[original_df_index]
sample_actual_score = y_test.iloc[sample_index]
sample_predicted_score = pred[sample_index]

print(f"Original Essay:\n{sample_essay}\n")
print(f"Actual Score: {sample_actual_score}")
print(f"Predicted Score: {sample_predicted_score}")

Original Essay:
Once upon a time there was a young girl named @CAPS1 she lived with her dad and mom in a small town of @PERSON2. It was mom in a small town of @PERSON2. It was almost her birth and she was so exited for this birthday because she was turning twelve. Twelve was here luckey number ever sience she was little. Her mom said they could go into town and go to chef @PERSON1 and eat out she agreed so that morning she woke up and dad made her some pancakes with fresh strawberrys on them she went out to go milk there cows for her parents. @CAPS1 hated milking there cows because they are very stuburn so she went out there and miked the cows in only @NUM1 minetts. @CAPS1 went back inside and put the milk on the table. @CAPS1 was starting to wonder if she was going  to get a birthday present, @CAPS1 decided it would be best if she was patient when her mom came home from work (she works at a dress making store) she said, Are you ready to go eat, @CAPS1 jumped And yeld yes, yes. So they rode in to town and parked at the restaurant, they walked in and the lights are off her dad got the light switch and all of her cloose family and friends where there and they yelled sprise @CAPS1 was is such a shock she yelled @CAPS3 you, @CAPS3 you, @CAPS3 you, and on a table was twelve presents, and under the table was a dog. Her mom & dad got her a dog. She name the dog wonder because every time she saw him she began to wonder about her  wonderful life. And she learned that great thing come when you are patient.

Actual Score: 18
Predicted Score: 18.48

In [ ]:
sample_index = 17
original_df_index = y_test.index[sample_index]

sample_essay = texts[original_df_index]
sample_actual_score = y_test.iloc[sample_index]
sample_predicted_score = pred[sample_index]

print(f"Original Essay:\n{sample_essay}\n")
print(f"Actual Score: {sample_actual_score}")
print(f"Predicted Score: {sample_predicted_score}")

Original Essay:
A time when I was patient. Two weeks ago @CAPS4 @CAPS2 said her @CAPS1 was coming. @CAPS4 grandma was happy so she bought her sister a bus ticket. Bus tickets cost a lot of money. It is @NUM1 dollar. That was a lot of money. She @CAPS11't miss this bus because I really want to see her. I could not wait. So she was suppose to be coming on @DATE1. She didn't come. I was sick so I called @CAPS4 @CAPS2 at her job. I said, "@CAPS2 why didn't @CAPS3 come." @CAPS4 @CAPS2 said," @CAPS5 she is coming you just have to be patient." @CAPS6, I said. Next day was @DATE2. "@CAPS2 is she here yet" I said. "@CAPS8, @CAPS5 be patient she will be here tomorrow." "@CAPS6, I understand."I gave up I thought that she was not coming. So @CAPS4 mom called @CAPS4 godmom. She said it was @CAPS6. So she told me she was going to @ORGANIZATION1. I love @ORGANIZATION1. I so good. I asked @CAPS4 @CAPS2. "@CAPS11 I have a @CAPS12. @ORGANIZATION2 cheese burger. I said @CAPS13 to @CAPS4 uncle and @CAPS4 mom said she was not coming. I told @CAPS4 mom I was not giving up she was coming. So I said I am hanging up. So I air hustled. @CAPS4 mom said to @CAPS4 uncle @CAPS14 "should I get her something to eat. I thought she ment @CAPS4 grandmother. So I thought for a while her who is her. So I called back @CAPS4 mom said ohh I get food for uncle @CAPS14 dog. I said, @PERSON1's?  For a dog? She said know dog food. So @CAPS4 mom got me from @CAPS4 god mothers house I could not walk because @CAPS4 legs, back, arm and every part that I @CAPS11 move on @CAPS4 body hurt. So @CAPS4 grandmother came to her house because we have a keys. So she said where @CAPS16? @CAPS4 uncle whispered something and I said she here! Ran in @CAPS4 uncle room and hug her I said how are you because when I went for @CAPS4 grandmother birthday. She live in south caroline so yeah. The is @CAPS4 writing. That is when I was patient. So I could wait for @CAPS4 mom's @CAPS1.

Actual Score: 12
Predicted Score: 18.96

# For Set 8

In [ ]:
df = data[data['essay_set'] == 8]
df = df[['essay', 'domain1_score']]

df = df.dropna()

df.head()

                                                   essay  domain1_score
12253   A long time ago when I was in third grade I h...             34
12254   Softball has to be one of the single most gre...             46
12255   Some people like making people laugh, I love ...             40
12256   "LAUGHTER"  @CAPS1 I hang out with my friends...             30
12257  Well ima tell a story about the time i got @CA...             26

In [ ]:
df.rename(columns={
    'essay': 'text',
    'domain1_score': 'score'
}, inplace=True)

In [ ]:
texts = df['text']
scores = df['score']

In [ ]:
embeddings = model.encode(
    texts.tolist(),
    show_progress_bar=True
)

Batches:   0%|          | 0/23 [00:00<?, ?it/s]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    embeddings,
    scores,
    test_size=0.2,
    random_state=42
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 578
Testing samples: 145

In [ ]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=200, n_jobs=-1, random_state=42)

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score

pred = regressor.predict(X_test)
mean_error_for_set8 = mean_squared_error(y_test, pred)

print("Mean Squared Error:", mean_squared_error(y_test, pred))
print("R2 Score:", r2_score(y_test, pred))

Mean Squared Error: 21.360693620689656
R2 Score: 0.23014796205667065

In [ ]:
sample_index = 8
original_df_index = y_test.index[sample_index]

sample_essay = texts[original_df_index]
sample_actual_score = y_test.iloc[sample_index]
sample_predicted_score = pred[sample_index]

print(f"Original Essay:\n{sample_essay}\n")
print(f"Actual Score: {sample_actual_score}")
print(f"Predicted Score: {sample_predicted_score}")

Original Essay:
                            Whats Laughter!How many friends do you really have? What relationships do you have with others? Well, I'm in high school and I usually don't have that many friends. But I have a few and one of my friends @CAPS4 friends with someone that I truly love. (@CAPS1 didn't know that) @CAPS2 year I was a freshmen and i went to the church with some of my friends and their was an @NUM1 grader that fell in the pond/water and I wasn't sure @CAPS20 @CAPS1 was @CAPS3 or not so I end up coming up to him and asked.Me; @CAPS4 you @CAPS3?, do you need some help?@CAPS1 said; @CAPS6, its @CAPS3 I just sprained my ankle.Me; @CAPS3, see you later then.Him. Later thanks for asking though.me; @CAPS9 sure, @CAPS6 problem! The next year when I'm a sophomore I didn't realized that @CAPS1 was going to be their as a freshmen! his name is @CAPS11 I was starting to hang out with him more because @CAPS1 was really funny and sweet.  We went to the @CAPS12 ball together and our other friends were their but i was worried about of some stuffs but @CAPS1 made it butter because at that time i was afraid that my ex was their. @CAPS11 was their to help me and I also didn't know how to dance and their was a song that was on and I didn't realized that i was dancing until @CAPS1 told me that I was so after was dancing with him I end up asking him @CAPS20 I can dance with one of our friends and @CAPS1 said a was able too so me and @PERSON1 ends up dancing and @CAPS1 was their when I needed him. We end up heading outside and I called @CAPS13 @CAPS14 to be picked up. So, in the mean time, we were outside waiting for her. We were laughing at some jokes that we @CAPS15 said to each other. Like one was that @CAPS1 @CAPS15 some thing in his @CAPS15 and acted like that it was a wand of some sort to the school building and @CAPS15 asked like that it was changed to a gingerbread house. Just about a week ago I end up sneaking up behind him and scared him so bad that I end up laughing and @CAPS1 was too. Because @CAPS1 usually doesn't get freaked out like that, and @CAPS1 told me that @CAPS1 is going to get me back and I'm starting to freak out from me not knowing what it @MONTH1 be. @CAPS11 is a great help when i need him!  The thing about laughter in life is that you would need eat ether way your upset or not in the mood.The main thing that was funny from my family is that we prank each other; like my sister would step out of the room and her soda is in the room that I'm in she still @CAPS15 about half of soda in the can their was mustard on the table and she hates mustard form the taste of it but my dad was thinking the same thing that I was wanting to do and that was to put a little bit of mustard in her soda. When she came back to the room I was smiling and my dad was looking at me also my @CAPS17. My sister ends up having some of the soda and she was looking at my @CAPS14 and was like;@CAPS16, who put mustard in my soda? My @CAPS17, @CAPS18, @CAPS14 and myself was laughing and she hates mustard!, @CAPS20 it was something that I didn't like and that was put in my soda I would've done this too. So, mostly I'm trying to say is that their is some laughter that is funny. not all laughter is not funny. Its butter @CAPS20 you don't prank people that is close to your heart because they @MONTH1 get mad at you. Like my sister, @PERSON2 was mad at me when it wasn't me it was my dad's idea.

Actual Score: 27
Predicted Score: 36.625

In [ ]:
sample_index = 56
original_df_index = y_test.index[sample_index]

sample_essay = texts[original_df_index]
sample_actual_score = y_test.iloc[sample_index]
sample_predicted_score = pred[sample_index]

print(f"Original Essay:\n{sample_essay}\n")
print(f"Actual Score: {sample_actual_score}")
print(f"Predicted Score: {sample_predicted_score}")

Original Essay:
@DATE1 what a night!! Me and my friends we were going to a @CAPS1 party at our dance coaches work. we had to dress up as elves and play with kids. It was fun, but after we were done with the party that's when the real fun began! After we changed out of our costumes and back into our regular clothes we started taking pictures. @CAPS3 were funny ones,cute one, and weird ones,all kinds of pictures. Anyways my friends and i didn't want to go home just yet so we decided that we should go to some places to take more pictures and have more fun! First stop was a school play ground but we couldn't stay because it was late and we weren't allowed inside so we decided to go to the discovery park i was driving and one of my friends in the passenger seat was taking pictures that turned out really funny. so when we got to the park my friend that was taking the pictures said  @CAPS2 i drive around the parking lot?" I said sure. we switched spots and off we went. She was a pretty good driver, but @CAPS3 was some scary moments that i felt we were going to die. ha ha. So she drove around and then went to the stop sign by a main road where she decided it would be a good time to switch back and i was yelling at her "@CAPS3's a car coming we @CAPS2 get in trouble", but no she didn't listen to me she got out so then i had to get out and we were yelling at each other and my friends in the back seat were yelling also not because we were mad but we didn't want to get caught and we were having a lot of fun. so i get back in the driver seat and we are all yelling " get in the car" but she laughing really hard saying " I wet my pants." we all started laughing because we thought she was kidding but oh no she was serious she was laughing so hard that she actually wet her pants! It was a good thing she had extra pants with her. So i had to back up the car so she could change behind this big metal thing. As she was changing we thought it would be really funny if we got a picture of her changing so i got the camera and stuck it out the window, but it was really dark even with the flash on so the picture didn't come out! she was laughing so hard that we teased her saying " keep it in". We still tease her a lot about it even though it's been two months. When ever we are laughing really hard and someone says " oh i think I'm gonna pee my pants" we look at @PERSON1 and say " @PERSON1 knows what that's like" we have too much fun teasing her about things she's done.  the next day we go and tell the rest of our friends that weren't with us what happened and they all started laughing as hard as we did. At the time she wasn't in the room with us when we told the rest of our friends, but when she walked in and we all stopped and saw her it was really hard to keep from laughing. now everyone knows about that night and @PERSON1's " accident". every now and then we make fun of her but she laughs along because we all know it could have been anyone of us. It still makes me laugh today not as much as it did back when it really happened, but you @CAPS2 still get a laugh on it every now and then."

Actual Score: 35
Predicted Score: 33.86

# Final Result

In [ ]:
average_mse = (
    mean_error_for_set1 +
    mean_error_for_set2 +
    mean_error_for_set3 +
    mean_error_for_set4 +
    mean_error_for_set5 +
    mean_error_for_set6 +
    mean_error_for_set7 +
    mean_error_for_set8
) / 8

print("Average Mean Squared Error:", average_mse)

Average Mean Squared Error: 4.295766024728887